### ISSUE TITLE
[Discussion] Add loki installation mechanism (opt-in, additional to promtail)

### ISSUE THREAD

**Issue by alexbarcelo** [patrickjahns/ansible-role-promtail#58]
First of all, this ansible role rocks! But I needed loki in addition to promtail, and there is a lot of common stuff.

I started a fork, but maybe you would be receptive to a PR. If you don't want anybody to mess with this repo and/or think that a loki installation should be in a standalone repo, I respect that and no need to keep reading :)

My main idea is to only share certain key shared configuration things (such as `system_user` and `system_group`, maybe `config_dir` and `tmp_dir`, probably `install_dir`) to a `loki_` prefix of variables. Things like version can be kept separated but defaulted like this:

```yaml
loki_version: "2.2.1"
promtail_version: "{{ loki_version }}"
```

(I can conceive the need to have different loki version and promtail version, and it may avoid unnecessary breaking changes for a lot of users, maybe?)

With some flags named `loki_install` and `promtail_install` the user can choose whether to install only promtail, only loki, or both. Loki and promtail are distributed under the same releases page (on grafana/loki github) so they are quite "a pack". Still, users may want to deploy them separately.

Does it make sense? If you don't want it here but have some suggestions, I would be happy to get your feedback.

**Comment by patrickjahns** [comment]
I understand that my response is very delayed on that topic and I believe this issue is currently no longer relevant.

Personally speaking, I do like to separate the concerns of roles. If someone wants to install loki, a dedicated role for that should be used.
Sharing information can be achieved by interpolation of variables in the playbook / variable files. So it's possible to share common configuration between roles, even thought they are completely independent from each other.

I hope you understand that I follow this principle of separating concerns
